#!/usr/bin/expect
set user xxxx
set gate xxx.xxx.xxx.xxx
set password 12345678
set token [lindex $argv 0]
set file [lindex $argv 1]
set server xxxxxx@xxx.xxxxx.xxx.xxxx
set password2 xxxxx
#This line enables the process and turn off confirmation to send files
spawn ftp -i ${gate}
expect "Name (xxxxx):"
send "${user}\r"
expect "Password:"
send "${password}${token}\r"
expect "ftp>"
send "user xxxxx\r"
expect "Password:"
send "xxxxx\r"
send "pwd\r"
send "cd xxxxx\r"
expect "successfully changed."
send "mput *\r"
interact
